ALTER SESSION SET CURRENT_SCHEMA = VS_13_EQUIPE_5;

CREATE TABLE USUARIO
(
    ID_USUARIO   INT PRIMARY KEY,
    NOME         VARCHAR2(100)        NOT NULL,
    EMAIL        VARCHAR2(100) UNIQUE NOT NULL,
    SENHA        VARCHAR2(100)        NOT NULL,
    TIPO_USUARIO VARCHAR2(12)         NOT NULL CHECK (TIPO_USUARIO IN ('ADMIN', 'CLIENTE', 'ESPECIALISTA'))
);

CREATE SEQUENCE SEQ_USUARIO
    START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;

CREATE TABLE ADMIN
(
    ID_ADMIN   INT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    CONSTRAINT FK_ID_USUARIO_ADMIN FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE SEQUENCE SEQ_ADMIN
    START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;

CREATE TABLE CLIENTE
(
    ID_CLIENTE INT PRIMARY KEY,
    ID_USUARIO INT UNIQUE NOT NULL,
    CPF        CHAR(11)   NOT NULL UNIQUE,
    CONSTRAINT FK_ID_USUARIO_CLIENTE FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE SEQUENCE SEQ_CLIENTE
    START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;

CREATE TABLE ESPECIALISTA
(
    ID_ESPECIALISTA INT PRIMARY KEY,
    ID_USUARIO      INT UNIQUE      NOT NULL,
    DOCUMENTO       CHAR(14) UNIQUE NOT NULL,
    CONSTRAINT FK_ID_USUARIO_ESPECIALISTA FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE SEQUENCE SEQ_ESPECIALISTA
    START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;

CREATE TABLE CONTATO
(
    ID_CONTATO   INT PRIMARY KEY,
    ID_USUARIO   INT          NOT NULL,
    DESCRICAO    VARCHAR2(255),
    NUMERO       CHAR(11),
    TIPO_CONTATO VARCHAR2(11) NOT NULL CHECK (TIPO_CONTATO IN ('RESIDENCIAL', 'COMERCIAL')),
    CONSTRAINT FK_ID_USUARIO_CONTATO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE SEQUENCE SEQ_CONTATO
    START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;

CREATE TABLE ESTADO
(
    ID_ESTADO INT PRIMARY KEY,
    nome VARCHAR2(50) UNIQUE NOT NULL
);

CREATE SEQUENCE SEQ_ESTADO
    START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;

CREATE TABLE ENDERECO
(
    ID_ENDERECO INT PRIMARY KEY,
    ID_USUARIO  INT           NOT NULL,
    ID_ESTADO   INT           NOT NULL,
    CEP         CHAR(8)       NOT NULL,
    LOGRADOURO  VARCHAR2(255) NOT NULL,
    NUMERO      VARCHAR2(10)  NOT NULL,
    COMPLEMENTO VARCHAR2(25),
    CIDADE      VARCHAR2(50)  NOT NULL,
    CONSTRAINT FK_ID_USUARIO_ENDERECO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT FK_ID_ESTADO_ENDERECO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
);

CREATE SEQUENCE SEQ_ENDERECO
    START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;

CREATE TABLE MUDA
(
    ID_MUDA         INT PRIMARY KEY,
    ID_ESPECIALISTA INT,
    ID_CLIENTE      INT,
    NOME            VARCHAR2(255) NOT NULL,
    NOME_CIENTIFICO VARCHAR2(255) NOT NULL,
    PORTE           VARCHAR2(8)   NOT NULL CHECK (PORTE IN ('PEQUENO', 'MEDIO', 'GRANDE')),
    AMBIENTE_IDEAL  VARCHAR2(50)  NOT NULL,
    DESCRICAO       VARCHAR2(255) NOT NULL,
    CONSTRAINT FK_ID_ESPECIALISTA_MUDA FOREIGN KEY (ID_ESPECIALISTA) REFERENCES ESPECIALISTA (ID_ESPECIALISTA),
    CONSTRAINT FK_ID_CLIENTE_MUDA FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE SEQUENCE SEQ_MUDA
    START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;

CREATE TABLE RELATORIO
(
    ID_RELATORIO    INT PRIMARY KEY,
    ID_CLIENTE      INT           NOT NULL,
    ID_ESPECIALISTA INT,
    ID_MUDA         INT           NOT NULL,
    ESTADO_MUDA     VARCHAR2(100) NOT NULL,
    SUGESTOES       VARCHAR2(255),
    AVALIACAO       DECIMAL(2, 1),
    CONSTRAINT FK_ID_ESPECIALISTA_RELATORIO FOREIGN KEY (ID_ESPECIALISTA) REFERENCES ESPECIALISTA (ID_ESPECIALISTA),
    CONSTRAINT FK_ID_CLIENTE_RELATORIO FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
    CONSTRAINT FK_ID_MUDA_RELATORIO FOREIGN KEY (ID_MUDA) REFERENCES MUDA (ID_MUDA)
);

CREATE SEQUENCE SEQ_RELATORIO
    START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;

CREATE TABLE ENTREGA
(
    ID_ENTREGA  INT PRIMARY KEY,
    ID_CLIENTE  INT NOT NULL,
    ID_ENDERECO INT NOT NULL,
    STATUS VARCHAR2(8) CHECK (STATUS IN('RECEBIDO', 'ENVIADO', 'ENTREGUE')),
    CONSTRAINT FK_ID_CLIENTE_ENTREGA FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
    CONSTRAINT FK_ID_ENDERECO_ENTREGA FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (ID_ENDERECO)
);

CREATE SEQUENCE SEQ_ENTREGA
    START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;

CREATE TABLE ENTREGA_MUDA
(
    ID_ENTREGA_MUDA INT PRIMARY KEY,
    ID_MUDA         INT NOT NULL,
    ID_ENTREGA      INT NOT NULL,
    CONSTRAINT FK_ID_MUDA_ENTREGA_MUDA FOREIGN KEY (ID_MUDA) REFERENCES MUDA (ID_MUDA),
    CONSTRAINT FK_ID_ENTREGA_ENTREGA_MUDA FOREIGN KEY (ID_ENTREGA) REFERENCES ENTREGA (ID_ENTREGA)
);

CREATE SEQUENCE SEQ_ENTREGA_MUDA
    START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;
